disabled_rules:
  - variable_name
  - function_parameter_count
  - nesting
line_length: 110
type_body_length:
  warning: 300
  error: 400
reporter: "xcode"
custom_rules:
  testable_prohibited:
    name: "@testable prohibited"
    regex: "@testable"
    message: "Do not use @testable in production code."
    severity: warning
